package sss.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MatchUI extends VerticalLayout {
	protected VerticalLayout teamsLayout;
	protected HorizontalLayout homeTeamLayout;
	protected Label homeTeamLabel;
	protected HorizontalLayout homeTeamYellow;
	protected HorizontalLayout awayTeamYellow;
	protected HorizontalLayout awayTeamLayout;
	protected Label awayTeamLabel;
	protected HorizontalLayout gametickerLayout;
	protected HorizontalLayout firstHalfLayout;
	protected ProgressBar firstHalfProgress;
	protected HorizontalLayout secondHalfLayout;
	protected ProgressBar secondHalfProgress;

	public MatchUI() {
		Design.read(this);
	}
}
